(* Created with the Wolfram Language : www.wolfram.com *)
{{{"Case ", "renormalization fb"}, {"tot bin syn", 1.148848395730919}, 
  {"all NS", 1.148848395730919}, {"NS+BH 2P crit", 1.148848395730919}, 
  {"tot bin syn without outliers", 1.1848776351568668}, 
  {"all NS without outliers", 1.191233206739054}, 
  {"NS+BH 2P crit without outliers", 1.184595995182094}}, {{}}, 
 Join[{{"", " detection integrated DSNB (\!\(\*SuperscriptBox[\(cm\), \
\(-2\)]\)\!\(\*SuperscriptBox[\(s\), \(-1\)]\))", 
    "EminKresse to EmaxKresse MeV"}, {"bin syn without outliers"}, 
   {"fiducialCE1", "all NS (no MSW)", int1030DSNBallNSwithout}, 
   {"", "all NS (IH)", int1030DSNBallNSwithoutIH}, 
   {"", "all NS (NH)", int1030DSNBallNSwithoutNH}, 
   {"", "NS+BH with 2P crit (no MSW)", int1030DSNB2Pwithout}, 
   {"", "NS+BH with 2P crit  (IH)", int1030DSNB2PwithoutIH}, 
   {"", "NS+BH with 2P crit  (NH)", int1030DSNB2PwithoutNH}}, peIntDSNBrow, 
  {{"no bin syn without outliers"}, {"", "all NS (no MSW)", 
    noint1030DSNBallNSwithout}, {"", "all NS (IH)", 
    noint1030DSNBallNSwithoutIH}, {"", "all NS (NH)", 
    noint1030DSNBallNSwithoutNH}, {"", "NS+BH with 2P crit (no MSW)", 
    noint1030DSNB2Pwithout}, {"", "NS+BH with 2P crit  (IH)", 
    noint1030DSNB2PwithoutIH}, {"", "NS+BH with 2P crit  (NH)", 
    noint1030DSNB2PwithoutNH}}], {{}}, 
 {{"bin syn without outliers", "SK-Gd Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"fiducialCE1", "All NS (no MSW)", skeventRateAllNSwithout}, 
  {"", "All NS (NH)", skeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", skeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", skeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", skeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", skeventRate1PwithoutIH}}, {{}}, 
 {{"no bin syn without outliers", "SK-Gd Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"", "All NS (no MSW)", noskeventRateAllNSwithout}, 
  {"", "All NS (NH)", noskeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", noskeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", noskeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", noskeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", noskeventRate1PwithoutIH}}, {{}}, 
 {{"progen+engine", "SK-Gd Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"W18-BH2.7-a2.0", "No MSW", peSKEventRate}, 
  {"", "with MSW (NH)", peSKEventRateNH}, {"", "with MSW (IH)", 
   peSKEventRateIH}}, {{}}, {{"bin syn without outliers", "HK Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"fiducialCE1", "All NS (no MSW)", hkeventRateAllNSwithout}, 
  {"", "All NS (NH)", hkeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", hkeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", hkeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", hkeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", hkeventRate1PwithoutIH}}, {{}}, 
 {{"no bin syn without outliers", "HK Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"", "All NS (no MSW)", nohkeventRateAllNSwithout}, 
  {"", "All NS (NH)", nohkeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", nohkeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", nohkeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", nohkeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", nohkeventRate1PwithoutIH}}, {{}}, 
 {{"progen+engine", "HK Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"W18-BH2.7-a2.0", "No MSW", peHKEventRate}, 
  {"", "with MSW (NH)", peHKEventRateNH}, {"", "with MSW (IH)", 
   peHKEventRateIH}}, {{}}, {{"bin syn without outliers", "JUNO Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"fiducialCE1", "All NS (no MSW)", JeventRateAllNSwithout}, 
  {"", "All NS (NH)", JeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", JeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", JeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", JeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", JeventRate1PwithoutIH}}, {{}}, 
 {{"no bin syn without outliers", "JUNO Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"", "All NS (no MSW)", noJeventRateAllNSwithout}, 
  {"", "All NS (NH)", noJeventRateAllNSwithoutNH}, 
  {"", "All NS (IH)", noJeventRateAllNSwithoutIH}, 
  {"", "NS+BH with criterion (no MSW)", noJeventRate1Pwithout}, 
  {"", "NS+BH with criterion (NH)", noJeventRate1PwithoutNH}, 
  {"", "NS+BH with criterion (IH)", noJeventRate1PwithoutIH}}, {{}}, 
 {{"progen+engine", "JUNO Event Rates", 
   "(\!\(\*SuperscriptBox[\(year\), \(-1\)]\))"}, 
  {"W18-BH2.7-a2.0", "No MSW", peJEventRate}, {"", "with MSW (NH)", 
   peJEventRateNH}, {"", "with MSW (IH)", peJEventRateIH}}}
